use_frameworks!

platform :ios, '10.0'

target 'PeachSDK_Example' do
  pod 'PeachSDK', :path => '../'

  target 'PeachSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
